### PR TITLE
fixed image loading issue

### PR DESCRIPTION
**Pull request by iamraghav**

### CODE REVIEW

**Comment by himanshuPawar1** [comment]
cool y the image was not loading

**Comment by iamraghav** [comment]
Some jquery initialization were missing

**Comment by himanshuPawar1** [comment]
ohk!!

**Comment by himanshuPawar1** [comment]
https://drive.google.com/open?id=1I0rQUKgZcsn-Wkvocq1XHD91TPDV3wHO

**Comment by himanshuPawar1** [comment]
https://drive.google.com/open?id=12fS5TtlH-4Y6OriIPiCCAOWn10Kn7Txn

**Comment by himanshuPawar1** [comment]
(check this one rar file)
https://drive.google.com/open?id=1B69RMkH62ZYHGzEzFDasLr8bg_nGl-bX

**Pull request merged**
